### ISSUE TITLE
Should specify the license

### ISSUE THREAD

**Issue by keeganwitt** [tambapps/groovy-shell-user-manual#1]
It's unclear what the license of this source is.  As a general practice, add a file called `LICENSE` with the license text to the repository root directory.

**Comment by tambapps** [comment]
This repository is just for documentation. It is only filled with `.md` files, there isn't any source code

Should I still add a LICENSE to it?

**Comment by keeganwitt** [comment]
It's a best practice, yes. I think there's two areas you are covering here. First, what (if any) permissions are needed to quote the text or use an image. Second, if someone wants to use part of a code sample as part of some other code, what are the rules around that?

Here are some examples of other documentation repositories that have a LICENSE (or COPYING) file. Some of them also have a CONTRIUBUTING and/or README file to describe how the can contribute to the documentation and how they can view/test rendered text changes (if applicable).

* https://github.com/dotnet/docs
* https://github.com/dotnet/AspNetCore.Docs
* https://github.com/raspberrypi/documentation
* https://github.com/tensorflow/docs
* https://github.com/cypress-io/cypress-documentation
* https://github.com/kubernetes/website
* https://github.com/purescript/documentation
* https://github.com/DataDog/documentation
* https://github.com/auth0/docs
* https://github.com/nextcloud/documentation
* https://github.com/opencollective/documentation

**Comment by tambapps** [comment]
Oh, ok I see. I've just added a LICENSE.

Thanks for the explanation!
